qlua run.lua -e true -p cuda -b 128  -f 1
qlua run.lua -e true -p cuda -b 128  -f 2
qlua run.lua -e true -p cuda -b 128  -f 3
qlua run.lua -e true -p cuda -b 128  -f 4
qlua run.lua -e true -p cuda -b 128  -f 5
qlua run.lua -e true -p cuda -b 128  -f 6
qlua run.lua -e true -p cuda -b 128  -f 7
qlua run.lua -e true -p cuda -b 128  -f 8
qlua run.lua -e true -p cuda -b 128  -f 9
qlua run.lua -e true -p cuda -b 128  -f 10
